<?php

add_action('init', function () {
	register_post_type('chronique', array(
		'labels' => array(
			'name' => 'Chroniques',
			'singular_name' => 'Chronique',
			'menu_name' => 'Chroniques',
			'all_items' => 'Toutes les Chroniques',
			'edit_item' => 'Modifier la Chronique',
			'view_item' => 'Voir la Chronique',
			'view_items' => 'Voir Chroniques',
			'add_new_item' => 'Ajouter une Chronique',
			'add_new' => 'Ajouter une Chronique',
			'new_item' => 'Nouvelle Chronique',
			'parent_item_colon' => 'Chronique parent :',
			'search_items' => 'Rechercher Chroniques',
			'not_found' => 'Aucune chroniques trouvé',
			'not_found_in_trash' => 'Aucune chronique trouvée dans la corbeille',
			'archives' => 'Archives des Chronique',
			'attributes' => 'Attributs des Chronique',
			'insert_into_item' => 'Insérer dans chronique',
			'uploaded_to_this_item' => 'Téléversé sur cette chronique',
			'filter_items_list' => 'Filtrer la liste des chroniques',
			'filter_by_date' => 'Filtrer les chroniques par date',
			'items_list_navigation' => 'Navigation dans la liste des Chroniques',
			'items_list' => 'Liste Chroniques',
			'item_published' => 'Chronique publié.',
			'item_published_privately' => 'Chronique publié en privé.',
			'item_reverted_to_draft' => 'Chronique repassé en brouillon.',
			'item_scheduled' => 'Chronique planifié.',
			'item_updated' => 'Chronique mis à jour.',
			'item_link' => 'Lien Chronique',
			'item_link_description' => 'Un lien vers une chronique.',
		),
		'public' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-admin-page',
		'menu_position' => 21,
		'supports' => array(
			0 => 'title',
			1 => 'editor',
			2 => 'thumbnail',
			3 => 'custom-fields',
		),
		'delete_with_user' => false,
		'show_ui' => true,
		'show_in_menu' => true,
		'has_archive' => false,
		'rewrite' => array(
			'slug' => 'chronique',
			'with_front' => false,
		),
	));
});

add_action('acf/include_fields', function () {
	if (!function_exists('acf_add_local_field_group')) {
		return;
	}

	acf_add_local_field_group(array(
		'key' => 'group_68a440dd84b6a',
		'title' => 'Sommaire d\'une Chronique',
		'fields' => array(
			array(
				'key' => 'field_68a440e3940bf',
				'label' => 'Titre sommaire',
				'name' => 'summary_title',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_68a440dd_mois_select',
				'label' => 'Mois de publication',
				'name' => 'publication_month',
				'type' => 'select',
				'instructions' => 'Sélectionnez le mois de publication.',
				'required' => 1,
				'choices' => array(
					'01' => 'Janvier',
					'02' => 'Février',
					'03' => 'Mars',
					'04' => 'Avril',
					'05' => 'Mai',
					'06' => 'Juin',
					'07' => 'Juillet',
					'08' => 'Août',
					'09' => 'Septembre',
					'10' => 'Octobre',
					'11' => 'Novembre',
					'12' => 'Décembre',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'wrapper' => array(
					'width' => '50',
				),
			),
			array(
				'key' => 'field_68a440dd_annee_select',
				'label' => 'Année de publication',
				'name' => 'publication_year',
				'type' => 'select',
				'instructions' => 'Sélectionnez l\'année de publication.',
				'required' => 1,
				'choices' => (function () {
					$years = array();
					$current_year = date('Y');
					for ($i = $current_year + 1; $i >= $current_year - 25; $i--) {
						$years[$i] = $i;
					}
					return $years;
				})(),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'wrapper' => array(
					'width' => '50',
				),
			),
			array(
				'key' => 'field_68a44209940c1',
				'label' => 'Image de couverture',
				'name' => 'cover_image',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_68a442b0940c2',
				'label' => 'Image de la couverture avec le magazine ouvert',
				'name' => 'cover_image_with_magazine_open',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_68a442ff940c3',
				'label' => 'Contenu du sommaire',
				'name' => 'summary_content',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'chronique',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));
});
