<?php

declare(strict_types=1);

/**
 * Register Custom Post-Type: Newsletter
 */
function amnesty_register_newsletter_cpt()
{
    $args = [
        'labels'       => [
            'name'               => 'Newsletter',
            'singular_name'      => 'Newsletter',
            'add_new'            => 'Créer une newsletter',
            'add_new_item'       => 'Créer une nouvelle newsletter',
            'edit_item'          => 'Modifier la newsletter',
            'new_item'           => 'Nouvelle newsletter',
            'view_item'          => 'Voir la newsletter',
            'search_items'       => 'Rechercher une newsletter',
            'not_found'          => 'Aucune newsletter trouvée',
            'not_found_in_trash' => 'Aucune newsletter dans la corbeille',
        ],
        'public'       => false,
        'has_archive'  => false,
        'menu_position' => 5,
        'rewrite'      => [ 'slug' => 'newsletter' ],
        'supports'     => [ 'title', 'custom-fields' ],
        'show_ui'      => true,
        'show_in_menu' => true,
        'show_in_rest' => false,
        'menu_icon'    => 'dashicons-email-alt',
    ];
    register_post_type('newsletter', $args);
}
add_action('init', 'amnesty_register_newsletter_cpt');

function amnesty_newsletter_preview_button(WP_Post $post)
{
    if ($post->post_type === 'newsletter' && $post->post_status === 'publish') {
        $url = admin_url('admin.php?page=newsletter_preview&newsletter_id=' . $post->ID);
        echo '<div class="misc-pub-section">';
        echo '<a href="' . esc_url($url) . '" target="_blank" class="button button-primary">Voir la newsletter</a>';
        echo '</div>';
    }
}
add_action('post_submitbox_misc_actions', 'amnesty_newsletter_preview_button');

function amnesty_newsletter_register_preview_page()
{
    add_submenu_page(
        null,
        'Preview newsletter',
        'Preview newsletter',
        'edit_posts',
        'newsletter_preview',
        'amnesty_newsletter_render_preview_page'
    );
}
add_action('admin_menu', 'amnesty_newsletter_register_preview_page');

function amnesty_newsletter_render_preview_page()
{
    include get_template_directory() . '/page-voir-newsletter.php';
}

add_action('acf/include_fields', function () {
    if (! function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group([
        'key' => 'group_68dbd6c6cb5e9',
        'title' => 'newsletter',
        'fields' => [
            [
                'key' => 'field_68d5044efa13c',
                'label' => 'Bloc 1',
                'name' => '1',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_68dbd250adbf2',
                        'label' => 'Titre',
                        'name' => 'titre',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Laisser le champ vide pour utiliser le titre du post par défaut',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_68dbd2afadbf3',
                        'label' => 'Image',
                        'name' => 'image',
                        'aria-label' => '',
                        'type' => 'file',
                        'instructions' => 'Laisser le champ vide pour utiliser l\'image du post par défaut',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => 'url',
                        'library' => 'all',
                        'min_size' => '',
                        'max_size' => '',
                        'mime_types' => 'jpg,jpeg,png,webp',
                        'allow_in_bindings' => 0,
                    ],
                    [
                        'key' => 'field_68d50678fa13f',
                        'label' => 'Accroche',
                        'name' => 'accroche',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'rows' => '',
                        'placeholder' => '',
                        'new_lines' => '',
                    ],
                    [
                        'key' => 'field_68d50683fa140',
                        'label' => 'Libellé du lien',
                        'name' => 'libelle_du_lien',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 'Voir',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_68d5069ffa141',
                        'label' => 'Lien',
                        'name' => 'lien',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'post_type' => [
                            0 => 'landmark',
                            1 => 'post',
                            2 => 'petition',
                            3 => 'page',
                        ],
                        'post_status' => [
                            0 => 'publish',
                        ],
                        'taxonomy' => '',
                        'return_format' => 'object',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'allow_in_bindings' => 0,
                        'bidirectional' => 0,
                        'ui' => 1,
                        'bidirectional_target' => [
                        ],
                    ],
                ],
            ],
            [
                'key' => 'field_68dbd60e7f16d',
                'label' => 'Bloc 2',
                'name' => '2',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_68d5069ffa141',
                            'operator' => '!=empty',
                        ],
                        [
                            'field' => 'field_68d50683fa140',
                            'operator' => '!=empty',
                        ],
                        [
                            'field' => 'field_68d50678fa13f',
                            'operator' => '!=empty',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_68dbd60e7f172',
                        'label' => 'Titre',
                        'name' => 'titre',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Laisser le champ vide pour utiliser le titre du post par défaut',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_68dbd60e7f173',
                        'label' => 'Image',
                        'name' => 'image',
                        'aria-label' => '',
                        'type' => 'file',
                        'instructions' => 'Laisser le champ vide pour utiliser l\'image du post par défaut',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => 'url',
                        'library' => 'all',
                        'min_size' => '',
                        'max_size' => '',
                        'mime_types' => 'jpg,jpeg,png,webp',
                        'allow_in_bindings' => 0,
                    ],
                    [
                        'key' => 'field_68dbd60e7f174',
                        'label' => 'Accroche',
                        'name' => 'accroche',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'rows' => '',
                        'placeholder' => '',
                        'new_lines' => '',
                    ],
                    [
                        'key' => 'field_68dbd60e7f175',
                        'label' => 'Libellé du lien',
                        'name' => 'libelle_du_lien',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 'Voir',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_68dbd60e7f176',
                        'label' => 'Lien',
                        'name' => 'lien',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'post_type' => [
                            0 => 'landmark',
                            1 => 'post',
                            2 => 'petition',
                            3 => 'page',
                        ],
                        'post_status' => [
                            0 => 'publish',
                        ],
                        'taxonomy' => '',
                        'return_format' => 'object',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'allow_in_bindings' => 0,
                        'bidirectional' => 0,
                        'ui' => 1,
                        'bidirectional_target' => [
                        ],
                    ],
                ],
            ],
            [
                'key' => 'field_68dbd66250fc4',
                'label' => 'Bloc 3',
                'name' => '3',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_68dbd60e7f176',
                            'operator' => '!=empty',
                        ],
                        [
                            'field' => 'field_68dbd60e7f175',
                            'operator' => '!=empty',
                        ],
                        [
                            'field' => 'field_68dbd60e7f174',
                            'operator' => '!=empty',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_68dbd66250fc9',
                        'label' => 'Titre',
                        'name' => 'titre',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Laisser le champ vide pour utiliser le titre du post par défaut',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_68dbd66250fca',
                        'label' => 'Image',
                        'name' => 'image',
                        'aria-label' => '',
                        'type' => 'file',
                        'instructions' => 'Laisser le champ vide pour utiliser l\'image du post par défaut',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => '',
                        'library' => '',
                        'min_size' => '',
                        'max_size' => '',
                        'mime_types' => 'jpg,jpeg,png,webp',
                        'allow_in_bindings' => 0,
                    ],
                    [
                        'key' => 'field_68dbd66250fcb',
                        'label' => 'Accroche',
                        'name' => 'accroche',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'rows' => '',
                        'placeholder' => '',
                        'new_lines' => '',
                    ],
                    [
                        'key' => 'field_68dbd66250fcc',
                        'label' => 'Libellé du lien',
                        'name' => 'libelle_du_lien',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 'Voir',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_68dbd66250fcd',
                        'label' => 'Lien',
                        'name' => 'lien',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'post_type' => [
                            0 => 'landmark',
                            1 => 'post',
                            2 => 'petition',
                            3 => 'page',
                        ],
                        'post_status' => [
                            0 => 'publish',
                        ],
                        'taxonomy' => '',
                        'return_format' => '',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'allow_in_bindings' => 0,
                        'bidirectional' => 0,
                        'ui' => 1,
                        'bidirectional_target' => [
                        ],
                    ],
                ],
            ],
            [
                'key' => 'field_68dbd67750fce',
                'label' => 'Bloc 4',
                'name' => '4',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_68dbd66250fcd',
                            'operator' => '!=empty',
                        ],
                        [
                            'field' => 'field_68dbd66250fcc',
                            'operator' => '!=empty',
                        ],
                        [
                            'field' => 'field_68dbd66250fcb',
                            'operator' => '!=empty',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_68dbd67750fd3',
                        'label' => 'Titre',
                        'name' => 'titre',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Laisser le champ vide pour utiliser le titre du post par défaut',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_68dbd67750fd4',
                        'label' => 'Image',
                        'name' => 'image',
                        'aria-label' => '',
                        'type' => 'file',
                        'instructions' => 'Laisser le champ vide pour utiliser l\'image du post par défaut',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => '',
                        'library' => '',
                        'min_size' => '',
                        'max_size' => '',
                        'mime_types' => 'jpg,jpeg,png,webp',
                        'allow_in_bindings' => 0,
                    ],
                    [
                        'key' => 'field_68dbd67750fd5',
                        'label' => 'Accroche',
                        'name' => 'accroche',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'rows' => '',
                        'placeholder' => '',
                        'new_lines' => '',
                    ],
                    [
                        'key' => 'field_68dbd67750fd6',
                        'label' => 'Libellé du lien',
                        'name' => 'libelle_du_lien',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 'Voir',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_68dbd67750fd7',
                        'label' => 'Lien',
                        'name' => 'lien',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'post_type' => [
                            0 => 'landmark',
                            1 => 'post',
                            2 => 'petition',
                            3 => 'page',
                        ],
                        'post_status' => [
                            0 => 'publish',
                        ],
                        'taxonomy' => '',
                        'return_format' => '',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'allow_in_bindings' => 0,
                        'bidirectional' => 0,
                        'ui' => 1,
                        'bidirectional_target' => [
                        ],
                    ],
                ],
            ],
            [
                'key' => 'field_68dbd68250fd8',
                'label' => 'Bloc 5',
                'name' => '5',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_68dbd67750fd7',
                            'operator' => '!=empty',
                        ],
                        [
                            'field' => 'field_68dbd67750fd6',
                            'operator' => '!=empty',
                        ],
                        [
                            'field' => 'field_68dbd67750fd5',
                            'operator' => '!=empty',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_68dbd68250fdd',
                        'label' => 'Titre',
                        'name' => 'titre',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Laisser le champ vide pour utiliser le titre du post par défaut',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_68dbd68250fde',
                        'label' => 'Image',
                        'name' => 'image',
                        'aria-label' => '',
                        'type' => 'file',
                        'instructions' => 'Laisser le champ vide pour utiliser l\'image du post par défaut',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => '',
                        'library' => '',
                        'min_size' => '',
                        'max_size' => '',
                        'mime_types' => 'jpg,jpeg,png,webp',
                        'allow_in_bindings' => 0,
                    ],
                    [
                        'key' => 'field_68dbd68250fdf',
                        'label' => 'Accroche',
                        'name' => 'accroche',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'rows' => '',
                        'placeholder' => '',
                        'new_lines' => '',
                    ],
                    [
                        'key' => 'field_68dbd68250fe0',
                        'label' => 'Libellé du lien',
                        'name' => 'libelle_du_lien',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 'Voir',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_68dbd68250fe1',
                        'label' => 'Lien',
                        'name' => 'lien',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'post_type' => [
                            0 => 'landmark',
                            1 => 'post',
                            2 => 'petition',
                            3 => 'page',
                        ],
                        'post_status' => [
                            0 => 'publish',
                        ],
                        'taxonomy' => '',
                        'return_format' => '',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'allow_in_bindings' => 0,
                        'bidirectional' => 0,
                        'ui' => 1,
                        'bidirectional_target' => [
                        ],
                    ],
                ],
            ],
            [
                'key' => 'field_68dbd68d50fe2',
                'label' => 'Bloc 6',
                'name' => '6',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_68dbd68250fe1',
                            'operator' => '!=empty',
                        ],
                        [
                            'field' => 'field_68dbd68250fe0',
                            'operator' => '!=empty',
                        ],
                        [
                            'field' => 'field_68dbd68250fdf',
                            'operator' => '!=empty',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_68dbd68d50fe7',
                        'label' => 'Titre',
                        'name' => 'titre',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Laisser le champ vide pour utiliser le titre du post par défaut',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_68dbd68d50fe8',
                        'label' => 'Image',
                        'name' => 'image',
                        'aria-label' => '',
                        'type' => 'file',
                        'instructions' => 'Laisser le champ vide pour utiliser l\'image du post par défaut',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => '',
                        'library' => '',
                        'min_size' => '',
                        'max_size' => '',
                        'mime_types' => 'jpg,jpeg,png,webp',
                        'allow_in_bindings' => 0,
                    ],
                    [
                        'key' => 'field_68dbd68d50fe9',
                        'label' => 'Accroche',
                        'name' => 'accroche',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'rows' => '',
                        'placeholder' => '',
                        'new_lines' => '',
                    ],
                    [
                        'key' => 'field_68dbd68d50fea',
                        'label' => 'Libellé du lien',
                        'name' => 'libelle_du_lien',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 'Voir',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_68dbd68d50feb',
                        'label' => 'Lien',
                        'name' => 'lien',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'post_type' => [
                            0 => 'landmark',
                            1 => 'post',
                            2 => 'petition',
                            3 => 'page',
                        ],
                        'post_status' => [
                            0 => 'publish',
                        ],
                        'taxonomy' => '',
                        'return_format' => '',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'allow_in_bindings' => 0,
                        'bidirectional' => 0,
                        'ui' => 1,
                        'bidirectional_target' => [
                        ],
                    ],
                ],
            ],
            [
                'key' => 'field_68dbd69b50fec',
                'label' => 'Bloc 7',
                'name' => '7',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_68dbd68d50feb',
                            'operator' => '!=empty',
                        ],
                        [
                            'field' => 'field_68dbd68d50fea',
                            'operator' => '!=empty',
                        ],
                        [
                            'field' => 'field_68dbd68d50fe9',
                            'operator' => '!=empty',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_68dbd69b50ff1',
                        'label' => 'Titre',
                        'name' => 'titre',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Laisser le champ vide pour utiliser le titre du post par défaut',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_68dbd69b50ff2',
                        'label' => 'Image',
                        'name' => 'image',
                        'aria-label' => '',
                        'type' => 'file',
                        'instructions' => 'Laisser le champ vide pour utiliser l\'image du post par défaut',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => '',
                        'library' => '',
                        'min_size' => '',
                        'max_size' => '',
                        'mime_types' => 'jpg,jpeg,png,webp',
                        'allow_in_bindings' => 0,
                    ],
                    [
                        'key' => 'field_68dbd69b50ff3',
                        'label' => 'Accroche',
                        'name' => 'accroche',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'rows' => '',
                        'placeholder' => '',
                        'new_lines' => '',
                    ],
                    [
                        'key' => 'field_68dbd69b50ff4',
                        'label' => 'Libellé du lien',
                        'name' => 'libelle_du_lien',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 'Voir',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_68dbd69b50ff5',
                        'label' => 'Lien',
                        'name' => 'lien',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'post_type' => [
                            0 => 'landmark',
                            1 => 'post',
                            2 => 'petition',
                            3 => 'page',
                        ],
                        'post_status' => [
                            0 => 'publish',
                        ],
                        'taxonomy' => '',
                        'return_format' => '',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'allow_in_bindings' => 0,
                        'bidirectional' => 0,
                        'ui' => 1,
                        'bidirectional_target' => [
                        ],
                    ],
                ],
            ],
            [
                'key' => 'field_68dbd6a650ff6',
                'label' => 'Bloc 8',
                'name' => '8',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_68dbd69b50ff5',
                            'operator' => '!=empty',
                        ],
                        [
                            'field' => 'field_68dbd69b50ff4',
                            'operator' => '!=empty',
                        ],
                        [
                            'field' => 'field_68dbd69b50ff3',
                            'operator' => '!=empty',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_68dbd6a650ffb',
                        'label' => 'Titre',
                        'name' => 'titre',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Laisser le champ vide pour utiliser le titre du post par défaut',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_68dbd6a650ffc',
                        'label' => 'Image',
                        'name' => 'image',
                        'aria-label' => '',
                        'type' => 'file',
                        'instructions' => 'Laisser le champ vide pour utiliser l\'image du post par défaut',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => '',
                        'library' => '',
                        'min_size' => '',
                        'max_size' => '',
                        'mime_types' => 'jpg,jpeg,png,webp',
                        'allow_in_bindings' => 0,
                    ],
                    [
                        'key' => 'field_68dbd6a650ffd',
                        'label' => 'Accroche',
                        'name' => 'accroche',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'rows' => '',
                        'placeholder' => '',
                        'new_lines' => '',
                    ],
                    [
                        'key' => 'field_68dbd6a650ffe',
                        'label' => 'Libellé du lien',
                        'name' => 'libelle_du_lien',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 'Voir',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_68dbd6a650fff',
                        'label' => 'Lien',
                        'name' => 'lien',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'post_type' => [
                            0 => 'landmark',
                            1 => 'post',
                            2 => 'petition',
                            3 => 'page',
                        ],
                        'post_status' => [
                            0 => 'publish',
                        ],
                        'taxonomy' => '',
                        'return_format' => '',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'allow_in_bindings' => 0,
                        'bidirectional' => 0,
                        'ui' => 1,
                        'bidirectional_target' => [
                        ],
                    ],
                ],
            ],
            [
                'key' => 'field_68dbd6b251000',
                'label' => 'Bloc 9',
                'name' => '9',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_68dbd6a650fff',
                            'operator' => '!=empty',
                        ],
                        [
                            'field' => 'field_68dbd6a650ffe',
                            'operator' => '!=empty',
                        ],
                        [
                            'field' => 'field_68dbd6a650ffd',
                            'operator' => '!=empty',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_68dbd6b251005',
                        'label' => 'Titre',
                        'name' => 'titre',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Laisser le champ vide pour utiliser le titre du post par défaut',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_68dbd6b251006',
                        'label' => 'Image',
                        'name' => 'image',
                        'aria-label' => '',
                        'type' => 'file',
                        'instructions' => 'Laisser le champ vide pour utiliser l\'image du post par défaut',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => '',
                        'library' => '',
                        'min_size' => '',
                        'max_size' => '',
                        'mime_types' => 'jpg,jpeg,png,webp',
                        'allow_in_bindings' => 0,
                    ],
                    [
                        'key' => 'field_68dbd6b251007',
                        'label' => 'Accroche',
                        'name' => 'accroche',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'rows' => '',
                        'placeholder' => '',
                        'new_lines' => '',
                    ],
                    [
                        'key' => 'field_68dbd6b251008',
                        'label' => 'Libellé du lien',
                        'name' => 'libelle_du_lien',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 'Voir',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_68dbd6b251009',
                        'label' => 'Lien',
                        'name' => 'lien',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'post_type' => [
                            0 => 'landmark',
                            1 => 'post',
                            2 => 'petition',
                            3 => 'page',
                        ],
                        'post_status' => [
                            0 => 'publish',
                        ],
                        'taxonomy' => '',
                        'return_format' => '',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'allow_in_bindings' => 0,
                        'bidirectional' => 0,
                        'ui' => 1,
                        'bidirectional_target' => [
                        ],
                    ],
                ],
            ],
            [
                'key' => 'field_68dbd6fe8f917',
                'label' => 'Bloc 10',
                'name' => '10',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_68dbd6b251009',
                            'operator' => '!=empty',
                        ],
                        [
                            'field' => 'field_68dbd6b251008',
                            'operator' => '!=empty',
                        ],
                        [
                            'field' => 'field_68dbd6b251007',
                            'operator' => '!=empty',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_68dbd6fe8f91c',
                        'label' => 'Titre',
                        'name' => 'titre',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Laisser le champ vide pour utiliser le titre du post par défaut',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_68dbd6fe8f91d',
                        'label' => 'Image',
                        'name' => 'image',
                        'aria-label' => '',
                        'type' => 'file',
                        'instructions' => 'Laisser le champ vide pour utiliser l\'image du post par défaut',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => 'array',
                        'library' => 'all',
                        'min_size' => '',
                        'max_size' => '',
                        'mime_types' => 'jpg,jpeg,png,webp',
                        'allow_in_bindings' => 0,
                    ],
                    [
                        'key' => 'field_68dbd6fe8f91e',
                        'label' => 'Accroche',
                        'name' => 'accroche',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'rows' => '',
                        'placeholder' => '',
                        'new_lines' => '',
                    ],
                    [
                        'key' => 'field_68dbd6fe8f91f',
                        'label' => 'Libellé du lien',
                        'name' => 'libelle_du_lien',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 'Voir',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_68dbd6fe8f920',
                        'label' => 'Lien',
                        'name' => 'lien',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'post_type' => [
                            0 => 'landmark',
                            1 => 'post',
                            2 => 'petition',
                            3 => 'page',
                        ],
                        'post_status' => [
                            0 => 'publish',
                        ],
                        'taxonomy' => '',
                        'return_format' => 'object',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'allow_in_bindings' => 0,
                        'bidirectional' => 0,
                        'ui' => 1,
                        'bidirectional_target' => [
                        ],
                    ],
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'newsletter',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ]);
});
