<?php



if (!function_exists('setup_countries')) {
    function setup_countries()
    {
        $countries_default = [
            'Algérie' => ['slug' => 'algerie'],
            'Afghanistan' => ['slug' => 'afghanistan'],
            'Afrique du Sud' => ['slug' => 'afrique-du-sud'],
            'Albanie' => ['slug' => 'albanie'],
            'Allemagne' => ['slug' => 'allemagne'],
            'Andorre' => ['slug' => 'andorre'],
            'Angola' => ['slug' => 'angola'],
            'Arabie Saoudite' => ['slug' => 'arabie-saoudite'],
            'Argentine' => ['slug' => 'argentine'],
            'Arménie' => ['slug' => 'armenie'],
            'Australie' => ['slug' => 'australie'],
            'Autriche' => ['slug' => 'autriche'],
            'Azerbaïdjan' => ['slug' => 'azerbaidjan'],
            'Bahrein' => ['slug' => 'bahrein'],
            'Bangladesh' => ['slug' => 'bangladesh'],
            'Bélarus' => ['slug' => 'belarus'],
            'Belgique' => ['slug' => 'belgique'],
            'Bénin' => ['slug' => 'benin'],
            'Bhoutan' => ['slug' => 'bhoutan'],
            'Bolivie' => ['slug' => 'bolivie'],
            'Bosnie-Herzégovine' => ['slug' => 'bosnie-herzegovine'],
            'Botswana' => ['slug' => 'botswana'],
            'Brésil' => ['slug' => 'bresil'],
            'Bulgarie' => ['slug' => 'bulgarie'],
            'Burkina Faso' => ['slug' => 'burkina-faso'],
            'Burundi' => ['slug' => 'burundi'],
            'Cambodge' => ['slug' => 'cambodge'],
            'Cameroun' => ['slug' => 'cameroun'],
            'Canada' => ['slug' => 'canada'],
            'Chili' => ['slug' => 'chili'],
            'Chine' => ['slug' => 'chine'],
            'Chypre' => ['slug' => 'chypre'],
            'Colombie' => ['slug' => 'colombie'],
            'Congo' => ['slug' => 'congo'],
            'Corée du Nord' => ['slug' => 'coree-du-nord'],
            'Corée du Sud' => ['slug' => 'coree-du-sud'],
            'Côte d\'Ivoire' => ['slug' => 'cote-divoire'],
            'Croatie' => ['slug' => 'croatie'],
            'Cuba' => ['slug' => 'cuba'],
            'Danemark' => ['slug' => 'danemark'],
            'Égypte' => ['slug' => 'egypte'],
            'Émirats Arabes Unis' => ['slug' => 'emirats-arabes-unis'],
            'Équateur' => ['slug' => 'equateur'],
            'Érythrée' => ['slug' => 'erythree'],
            'Espagne' => ['slug' => 'espagne'],
            'Eswatini' => ['slug' => 'eswatini'],
            'État de Palestine' => ['slug' => 'palestine-etat-de'],
            'États-Unis' => ['slug' => 'etats-unis'],
            'Éthiopie' => ['slug' => 'ethiopie'],
            'Fidji' => ['slug' => 'fidji'],
            'Finlande' => ['slug' => 'finlande'],
            'France' => ['slug' => 'france'],
            'Gambie' => ['slug' => 'gambie'],
            'Géorgie' => ['slug' => 'georgie'],
            'Ghana' => ['slug' => 'ghana'],
            'Grèce' => ['slug' => 'grece'],
            'Guatemala' => ['slug' => 'guatemala'],
            'Guinée' => ['slug' => 'guinee'],
            'Guinée Équatoriale' => ['slug' => 'guinee-equatoriale'],
            'Haïti' => ['slug' => 'haiti'],
            'Honduras' => ['slug' => 'honduras'],
            'Hongrie' => ['slug' => 'hongrie'],
            'Inde' => ['slug' => 'inde'],
            'Indonésie' => ['slug' => 'indonesie'],
            'Irak' => ['slug' => 'irak'],
            'Iran' => ['slug' => 'iran'],
            'Irlande' => ['slug' => 'irlande'],
            'Israël et Territoires Palestiniens occupés' => ['slug' => 'israel-et-territoires-occupes'],
            'Italie' => ['slug' => 'italie'],
            'Japon' => ['slug' => 'japon'],
            'Jordanie' => ['slug' => 'jordanie'],
            'Kazakhstan' => ['slug' => 'kazakhstan'],
            'Kenya' => ['slug' => 'kenya'],
            'Kirghizistan' => ['slug' => 'kirghizistan'],
            'Kosovo' => ['slug' => 'kosovo'],
            'Koweït' => ['slug' => 'koweit'],
            'Laos' => ['slug' => 'laos'],
            'Lesotho' => ['slug' => 'lesotho'],
            'Lettonie' => ['slug' => 'lettonie'],
            'Liban' => ['slug' => 'liban'],
            'Libye' => ['slug' => 'libye'],
            'Lituanie' => ['slug' => 'lituanie'],
            'Macédoine du Nord' => ['slug' => 'macedoine'],
            'Madagascar' => ['slug' => 'madagascar'],
            'Malaisie' => ['slug' => 'malaisie'],
            'Malawi' => ['slug' => 'malawi'],
            'Maldives' => ['slug' => 'maldives'],
            'Mali' => ['slug' => 'mali'],
            'Malte' => ['slug' => 'malte'],
            'Maroc et Sahara Occidental' => ['slug' => 'maroc'],
            'Mauritanie' => ['slug' => 'mauritanie'],
            'Mexique' => ['slug' => 'mexique'],
            'Moldavie' => ['slug' => 'moldavie'],
            'Mongolie' => ['slug' => 'mongolie'],
            'Monténégro' => ['slug' => 'montenegro'],
            'Mozambique' => ['slug' => 'mozambique'],
            'Myanmar' => ['slug' => 'myanmar'],
            'Namibie' => ['slug' => 'namibie'],
            'Népal' => ['slug' => 'nepal'],
            'Nicaragua' => ['slug' => 'nicaragua'],
            'Niger' => ['slug' => 'niger'],
            'Nigeria' => ['slug' => 'nigeria'],
            'Norvège' => ['slug' => 'norvege'],
            'Nouvelle-Zélande' => ['slug' => 'nouvelle-zelande'],
            'Oman' => ['slug' => 'oman'],
            'Ouganda' => ['slug' => 'ouganda'],
            'Ouzbékistan' => ['slug' => 'ouzbekistan'],
            'Pakistan' => ['slug' => 'pakistan'],
            'Papouasie-Nouvelle-Guinée' => ['slug' => 'papouasie-nouvelle-guinee'],
            'Paraguay' => ['slug' => 'paraguay'],
            'Pays-Bas' => ['slug' => 'pays-bas'],
            'Pérou' => ['slug' => 'perou'],
            'Philippines' => ['slug' => 'philippines'],
            'Pologne' => ['slug' => 'pologne'],
            'Porto Rico' => ['slug' => 'porto-rico'],
            'Portugal' => ['slug' => 'portugal'],
            'Qatar' => ['slug' => 'qatar'],
            'République Centrafricaine' => ['slug' => 'republique-centrafricaine'],
            'République Démocratique du Congo' => ['slug' => 'republique-democratique-du-congo'],
            'République Dominicaine' => ['slug' => 'republique-dominicaine'],
            'République Tchèque' => ['slug' => 'republique-tcheque'],
            'Roumanie' => ['slug' => 'roumanie'],
            'Royaume-Uni' => ['slug' => 'royaume-uni'],
            'Russie' => ['slug' => 'russie'],
            'Rwanda' => ['slug' => 'rwanda'],
            'Salvador' => ['slug' => 'salvador'],
            'Sénégal' => ['slug' => 'senegal'],
            'Serbie' => ['slug' => 'serbie'],
            'Sierra Leone' => ['slug' => 'sierra-leone'],
            'Singapour' => ['slug' => 'singapour'],
            'Slovaquie' => ['slug' => 'slovaquie'],
            'Slovénie' => ['slug' => 'slovenie'],
            'Somalie' => ['slug' => 'somalie'],
            'Soudan' => ['slug' => 'soudan'],
            'Soudan du Sud' => ['slug' => 'soudan-du-sud'],
            'Sri-Lanka' => ['slug' => 'sri-lanka'],
            'Suède' => ['slug' => 'suede'],
            'Suisse' => ['slug' => 'suisse'],
            'Syrie' => ['slug' => 'syrie'],
            'Tadjikistan' => ['slug' => 'tadjikistan'],
            'Taïwan' => ['slug' => 'taiwan'],
            'Tanzanie' => ['slug' => 'tanzanie'],
            'Tchad' => ['slug' => 'tchad'],
            'Thaïlande' => ['slug' => 'thailande'],
            'Togo' => ['slug' => 'togo'],
            'Tunisie' => ['slug' => 'tunisie'],
            'Turkménistan' => ['slug' => 'turkmenistan'],
            'Turquie' => ['slug' => 'turquie'],
            'Ukraine' => ['slug' => 'ukraine'],
            'Uruguay' => ['slug' => 'uruguay'],
            'Venezuela' => ['slug' => 'venezuela'],
            'Viêt-Nam' => ['slug' => 'viet-nam'],
            'Yémen' => ['slug' => 'yemen'],
            'Zambie' => ['slug' => 'zambie'],
            'Zimbabwe' => ['slug' => 'zimbabwe']
        ];

        foreach ($countries_default as $nom => $details) {
            if (!term_exists($details['slug'], 'location')) {
                wp_insert_term(
                    $nom,
                    'location',
                    array('slug' => $details['slug'])
                );
            }
        }
    }

    add_action('after_switch_theme', 'setup_countries');
}
