<?php

add_action('enqueue_block_editor_assets', function () {
    ?>
    <script>
    (function() {
        const originalError = console.error;
        console.error = function(...args) {
            if (
                args.length &&
                typeof args[0] === 'string' &&
                (
                    args[0].includes('Block validation failed') ||
                    args[0].includes('Content generated by `save` function:') ||
                    args[0].includes('Content retrieved from post body:')
                )
            ) {
                return;
            }
            originalError.apply(console, args);
        };
    })();
    </script>
    <?php
});
