<?php

require_once __DIR__ . '/MapperFactory.php';
require_once __DIR__ . '/BlockMapper.php';

require_once __DIR__ . '/rich-text/AgirLegacyMapper.php';
require_once __DIR__ . '/rich-text/BlockQuoteMapper.php';
require_once __DIR__ . '/rich-text/ChapoMapper.php';
require_once __DIR__ . '/rich-text/EmbedMapper.php';
require_once __DIR__ . '/rich-text/ExergueMapper.php';
require_once __DIR__ . '/rich-text/HeadingMapper.php';
require_once __DIR__ . '/rich-text/ImageMapper.php';
require_once __DIR__ . '/rich-text/ListMapper.php';
require_once __DIR__ . '/rich-text/ParagraphMapper.php';
require_once __DIR__ . '/rich-text/ReadAlsoMapper.php';

require_once __DIR__ . '/slices/AccordionMapper.php';
require_once __DIR__ . '/slices/AgirSliceMapper.php';
require_once __DIR__ . '/slices/BlocFocusMapper.php';
require_once __DIR__ . '/slices/BlocInfoMapper.php';
require_once __DIR__ . '/slices/BlocInfoRicheMapper.php';
require_once __DIR__ . '/slices/BlocOrangeMapper.php';
require_once __DIR__ . '/slices/ButtonMapper.php';
require_once __DIR__ . '/slices/CallToActionMapper.php';
require_once __DIR__ . '/slices/ChiffreClefMapper.php';
require_once __DIR__ . '/slices/ContenuHtmlMapper.php';
require_once __DIR__ . '/slices/ContenuSupplementaireMapper.php';
require_once __DIR__ . '/slices/ContenuSupplementaireSpecialMapper.php';
require_once __DIR__ . '/slices/CTAPushMapper.php';
require_once __DIR__ . '/slices/EncadreLienMapper.php';
require_once __DIR__ . '/slices/ImageEtLegendeMapper.php';
require_once __DIR__ . '/slices/LiensCartesMapper.php';
require_once __DIR__ . '/slices/ListeDActionsMapper.php';
require_once __DIR__ . '/slices/ListeDocumentsMapper.php';
require_once __DIR__ . '/slices/ListeFilmsMapper.php';
require_once __DIR__ . '/slices/MaterielMapper.php';
require_once __DIR__ . '/slices/MiseAJourMapper.php';
require_once __DIR__ . '/slices/PostTwitterMapper.php';
require_once __DIR__ . '/slices/PromotionPageMapper.php';
require_once __DIR__ . '/slices/SectionMapper.php';
require_once __DIR__ . '/slices/SectionImageMapper.php';
require_once __DIR__ . '/slices/SignatureEditoMapper.php';
require_once __DIR__ . '/slices/SlideshowMapper.php';
require_once __DIR__ . '/slices/SommaireMapper.php';
require_once __DIR__ . '/slices/TemoignagePhoto.php';
require_once __DIR__ . '/slices/TexteIllustreMapper.php';
require_once __DIR__ . '/slices/TrombiMapper.php';
require_once __DIR__ . '/slices/WrapImageMapper.php';
require_once __DIR__ . '/slices/VerbatimsMapper.php';
