name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

jobs:
  php-checks:
    name: PHP Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
      - name: Validate Composer configuration
        run: composer validate
      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist
      - name: Run PHP-CS-Fixer
        run: composer run cs
      - name: Run PHPStan
        run: composer run analyse -- --no-progress --error-format=github

  github-actions:
    name: GitHub Actions Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run ActionLint
        uses: docker://rhysd/actionlint:latest
