name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run PHP-CS-Fixer (PHP 8.2)
        uses: docker://oskarstark/php-cs-fixer-ga:3.25.0
        with:
          args: --config=.php-cs-fixer.php --diff --dry-run
