name: Deploy to Clever Cloud

on:
  workflow_call:
    inputs:
      app-id:
        description: Clever Cloud APP Id
        required: true
        type: string
    secrets:
      clever-token:
        description: Clever Cloud Token
        required: true
      clever-secret:
        description: Clever Cloud Secret
        required: true

env:
  APP_ID: ${{ inputs.app-id }}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy
      env:
        CC_VERSION: latest
        CLEVER_TOKEN: ${{ secrets.clever-token }}
        CLEVER_SECRET: ${{ secrets.clever-secret }}
      run: |
        curl -s -O https://clever-tools.clever-cloud.com/releases/${CC_VERSION}/clever-tools-${CC_VERSION}_linux.tar.gz
        tar -xvf clever-tools-${CC_VERSION}_linux.tar.gz
        export PATH=${PATH}:$(pwd)/clever-tools-${CC_VERSION}_linux
        git fetch --unshallow || git fetch --all
        clever link $APP_ID
        clever deploy -p ignore # if already deployed, do nothing
