name: Deploy to Clever Cloud

on:
  push:
    branches: [ "prod" ]

permissions:
  contents: read

jobs:
  deploy:
    name: PROD Espace Don
    uses: coopTilleuls/action-clevercloud-deploy/.github/workflows/deploy.yml@v1
    with:
      # variable APP_ID and secrets CLEVER_TOKEN and CLEVER_SECRET
      # must be defined in this github environment
      deploy-environment: PROD
    secrets:
      clever-token: ${{ secrets.CLEVER_TOKEN }}
      clever-secret: ${{ secrets.CLEVER_SECRET }}
