name: Deploy to Clever Cloud

on:
  push:
    branches: [ "cicd/fairness" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy on Fairness preprod
    environment: FAIRNESS
    uses: ./.github/workflows/clevercloud-deploy.yml
    with:
      app-id: ${{ vars.APP_ID }}
    secrets:
      clever-token: ${{ secrets.CLEVER_TOKEN }}
      clever-secret: ${{ secrets.CLEVER_SECRET }}
